spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Artur-Neves/microsservices-config-server
          search-paths:
            - 'greeting_service*'
#  config:
#    import:
server:
  port: 8888



